#!/bin/bash

./bin/braunFightersGPU &
GPUpid=$!
./bin/braunFightersCPU &
CPUpid=$!

echo $GPUpid > bin/GPUpid
echo $CPUpid > bin/CPUpid

sleep 1
kill -RTMIN $CPUpid
kill -RTMIN $GPUpid

while sleep 1; do
    kill -0 $GPUpid
    GPUstatus=$?
    kill -0 $CPUpid
    CPUstatus=$?

    if ( expr $GPUstatus + $CPUstatus > /dev/null ); then
        echo "GPU $GPUstatus  CPU $CPUstatus"
        kill -KILL $GPUpid
        kill -KILL $CPUpid
        exit
    fi
done