#!/bin/bash

mkdir bin 2> /dev/null

files=( "CPUmain.cpp" "sources/CPU.cpp" )
libs=(  )
flags=( "-O2" )
warns=( "-Wfatal-errors" "-Wno-unused-result" )

g++ ${files[@]} -o bin/braunFightersCPU ${flags[@]} ${warns[@]}